### ISSUE TITLE
How do you maintain your discipline?

### ISSUE THREAD

**Issue by mr-mig** [practicingdev/ama#3]
Do you have a strict schedule? Some good habits?

**Comment by practicingdev** [comment]
Depending on what kind of work I'm doing, this varies quite a bit. What I've learned though is that you need to have some sort of system if you want to avoid painful rollercoaster rides of disorganization and stress.

In the past when I've served as a team lead / account management person I explicitly set aside huge chunks of my day for interruptions, and then scheduled my heads down work for early mornings and weekends. Now that I'm working on my own again and have a very light client work load at the moment, my schedule is kind of the opposite.

I set aside specific blocks of time each week for planned work, which might account for 60-70% of my actual work week... I make sure to leave some slack for unplanned + urgent work, or to slot some extra blocks if I need to to move things along further. Without the slack... it's easy to overbook work and that starts to interfere with my household and child care responsibilities.

I'm trying to "call my shots" at least a day or two in advance, plotting out what I expect to do in each time box so that I already know what I'll be working on once I sit down to work. The calendar below shows how that works:
 
<img width="1235" alt="screen shot 2017-06-07 at 3 48 17 pm" src="https://user-images.githubusercontent.com/18146637/26898328-6e1abc1a-4b99-11e7-8eb1-0aaf6b91ad1b.png">

I break things up further by using the [Pomodoro technique](https://cirillocompany.de/pages/pomodoro-technique) in increments of 25 minutes with 5 minute breaks in between. I use the breaks to walk around a little bit and get some water, etc... but much more importantly they serve as a cut point so that I don't go too deep into something without asking "am I stuck? Is this going to take too long? Should I move on to something else?" etc. The app I use for this is great, but apparently no longer available in the MacOS app store. It looks like this, though:
<img width="347" alt="screen shot 2017-06-07 at 4 00 58 pm" src="https://user-images.githubusercontent.com/18146637/26898815-31df8c10-4b9b-11e7-9a07-8b96a7302a46.png">

To sum all of this up, I'd say my current approach is "Strict discipline, in moderation." There are lots of other ways I'm applying that general idea that I don't have time to explain right now, but the general idea is... you can be very focused and very structured in how you do things, as long as you leave plenty of slack for unstructured time as well (or at least shifting to a different structure).

In the past, I've tended to overdo it with rules for myself which eventually lead to me throw them all out and start from scratch after a rough crash. Now I tend to value that which I can consistently do. You want to be disciplined, not brittle, and I've often confused those two things.

Hope that helps!

**Comment by pavsaund** [comment]
This. 
> In the past, I've tended to overdo it with rules for myself which eventually lead to me throw them all out and start from scratch after a rough crash. Now I tend to value that which I can consistently do. You want to be disciplined, not brittle, and I've often confused those two things.

Having guiding systems I'm place and not rigid rules to follow makes a lot of sense. I have so far failed quite elegantly at this. I like the idea of planning chunks of time and leaving slack in between. But surely there are still days where things just don't work as planned, and the schedule falls apart?

**Comment by pavsaund** [comment]
Also, I see you haven't blocked off any "family" or "personal" time. What are your thoughts around that?

**Comment by practicingdev** [comment]
> But surely there are still days where things just don't work as planned, and the schedule falls apart?

Yes, and what I've been trying to do when that happens is update the schedule so that it becomes an intentional choice rather than something that just gets lost. It's easier to see the impact this way.

> Also, I see you haven't blocked off any "family" or "personal" time. What are your thoughts around that?

This is my work calendar, so I track that separately. I'm with my kids during the day for about 5 hours when my wife is at her work, and we're trying to keep weekends open as best as we can. So I'm flowing my work around the family time rather than the other way around at this point.

Personal time... I still don't really schedule it so I need to fill it in the gaps wherever I can. That's something I want to be more intentional about in the future.
