### ISSUE TITLE
What do you look for in a mentee or group of followers?

### ISSUE THREAD

**Issue by ghost** [practicingdev/ama#4]
I'm impressed with how you maintain your social media presence, and seem make connections that are more organic.  How does this play a role in your growth as a human/developer?  Would this tend to give you insight in finding your people?

**Comment by practicingdev** [comment]
Hi Jason,

When it comes to building a following... to be honest, I feel like if I was able to serve in an individual contributor role comfortably, I wouldn't make use of social media at all.

But my own work... it's mostly about tapping into experiences and insights of the industry as a whole, so that I can bring that into specialized settings (i.e. consulting work, training, writing projects, etc.)

And so I work really hard on building connections online that are mostly 1:1, and with an emphasis on depth. Although those who follow me might occasionally buy a book of mine or jump into a course, etc... I haven't made a whole ton of money that way. However, my online connections have given me near continuous access to immediate feedback on pretty much any topic I'd like to get into, and I feel like it's a very powerful learning engine for me.

There's a virtuous cycle, the more I connect with people, the more I learn, which makes it easier for me to produce good learning materials to teach others, and then it repeats from there. I make my living from occasionally applying what I've learned in commercial projects.

As for mentorship, I am very formal about that, and so there are only a couple people who I've ever accepted into that sort of role with me. Because to me mentorship is a holistic, multi-year commitment... it's not equivalent to just giving occasional support/training/coaching (which I also do). Because I just finished running a 1.5 year long apprenticeship program, I don't see myself being a mentor to anyone else for quite a while... though I do hope to do it again at some point in life.

I would say that I wouldn't consider mentoring someone I've had fewer than one hundred high quality conversations with. Which explains why this is so rare for me. :smile:

**Comment by practicingdev** [comment]
One more thing... I think I spend way more than half of my time interacting with beginner and intermediate level developers for three reasons:

1) Sometimes things that are easy for me are very helpful to them, and so that works well on both sides.

2) I know anyone who is in the early stages of their career will eventually (in a few years or so at most) be much better than me at something or the other, if they don't already have some skill that's more developed of my own. So I think very long term and realize... I may be helping them right now, but there may come a time in the future where I'll be able to learn from them, too.

3) Experts (and permanent-intermediates) are more likely to have made up their minds about things. People earlier on in their career are more curious and tend to shine light into blind spots that industry leaders miss, even if it's by accident.
