### ISSUE TITLE
Gregory, I know you can't preview the future, however, where are you gonna be in within 10 years?

### ISSUE THREAD

**Issue by matheusgontijo** [practicingdev/ama#6]
**First off, I completely understand there is no way to preview the future**.

Let me break it down a bit further in order to get an accurate answer.

I ask you this because many many great Software Developers down the road usually leave coding and become:

- Manager - _constantly the Enterprise field compels them to go to a higher level_
- Consultant - _using their wide experience to help other companies out_
- Company's Founder - _they figure out a fantastic idea and try to accomplish that (like Facebook, Netflix, Airbnb)_
- OR are you going to be coding UNTIL the last day of your career?

I appreciate your AMA channel.

**Comment by practicingdev** [comment]
Thanks for the question.

I've been in a consultant role for a good portion of my career already, and have also had a fair amount management responsibilities throughout the last decade. I like both kinds of work, though they're not super compatible with one another, and they're even less compatible with writing a good amount of code day to day.

I also spent 18 months out of the last two years running an apprenticeship program, and the interesting thing about that is that during that time I wrote very little code but built a tremendous amount of software. I would jump down to the code level whenever it was needed, to explain a concept or sort out a problem, but for the most part working with my apprentice left me able to focus on the external aspects of software development: Making sure we were building the thing the client needed, focusing on UX details, quality assurance, etc.

That was a really interesting experience, and something I'd like to do more of.

That said, you asked about my future. In ten years from now, I'd say that if I had to code every day in order to make a living, I'd consider that a failure, but I'd also consider not being able to code when I wanted to (due to a lack of time or atrophied skills), I'd think of that as a failure too.

So right now I'm trying to create a balanced approach where I do some teaching/writing around software development, some management consulting, and some product development. The first category keeps me thinking about what it's like to be learning technology and requires me to know enough to teach it, the second gives me a specialization in an area that pays well and isn't tied to a particular technology, and the final category is where I expect I'll be doing a lot of coding.

I haven't decided yet whether... in the long run... I'd want to build a company with a small team in which much of the day-to-day coding responsibilities would be handled by someone else, or if I want to stay on the sort of solopreneur route which involves mostly building things myself and then maybe contracting out whenever I need a specific project done.

Right now getting back into web development has me feeling a little rusty after being in higher level roles for the last couple years, and I don't like that feeling. I guess my path will depend on how quickly I can shake that off. :-P

In any case, I think what you might really be asking is... what's the path for someone who wants to code all day, every day? I think it's probably to gain some very deep technical specialization, and then find a sleepy corner of some big company that will pay you well to be the local expert in Thing X. But that's not a path that's ever been particularly interesting to me, and I view my technical skillset as a means to an end.

Hope that helps in some way! Happy to continue a discussion here if you have followup questions.
